server:
  port: 8083

spring:
  application:
    name: ftgo-order-service
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
