apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-restaurant-service-config
  labels:
    app.kubernetes.io/name: ftgo-restaurant-service
    app.kubernetes.io/component: service
data:
  SPRING_APPLICATION_NAME: ftgo-restaurant-service
  SERVER_PORT: "8082"
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/ftgo
  KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/ftgo/protocol/openid-connect/certs
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
