apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
spec:
  encryptedData:
    DB_USERNAME: AgBY...PLACEHOLDER...sealed-with-kubeseal
    DB_PASSWORD: AgBY...PLACEHOLDER...sealed-with-kubeseal
  template:
    metadata:
      name: keycloak-db-credentials
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: identity
    type: Opaque
