apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftgo-prod

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: false

resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/ingress-tls.yaml

images:
  - name: ghcr.io/mbatchelor81/ftgo-consumer-service
    newTag: latest
  - name: ghcr.io/mbatchelor81/ftgo-restaurant-service
    newTag: latest
  - name: ghcr.io/mbatchelor81/ftgo-order-service
    newTag: latest
  - name: ghcr.io/mbatchelor81/ftgo-courier-service
    newTag: latest
