plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.spring.dependency-management'
}

group = 'com.ftgo'
version = '1.0.0'
sourceCompatibility = '11'
targetCompatibility = '11'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:2.6.3'
    }
}

dependencies {
    api project(':services:ftgo-common')
    api 'org.springframework.boot:spring-boot-starter-data-jpa'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            groupId = 'com.ftgo'
            artifactId = 'ftgo-common-jpa'
            version = '1.0.0'
        }
    }
    repositories {
        maven {
            name = 'local'
            url = layout.buildDirectory.dir('repo')
        }
    }
}
