apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-consumer-service
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-restaurant-service
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-order-service
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-courier-service
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-api-gateway
spec:
  replicas: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-consumer-service
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-restaurant-service
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-order-service
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-courier-service
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-api-gateway
spec:
  minReplicas: 2
  maxReplicas: 6
