apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-mysql-config
  labels:
    app.kubernetes.io/name: ftgo-mysql
    app.kubernetes.io/component: database
data:
  MYSQL_DATABASE: ftgo
  MYSQL_USER: ftgo
