apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftgo-mysql-data
  labels:
    app.kubernetes.io/name: ftgo-mysql
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
