global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting-rules.yml"

scrape_configs:
  - job_name: "ftgo-consumer-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ftgo-consumer-service:8081"]
        labels:
          service: "consumer-service"

  - job_name: "ftgo-restaurant-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ftgo-restaurant-service:8082"]
        labels:
          service: "restaurant-service"

  - job_name: "ftgo-order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ftgo-order-service:8083"]
        labels:
          service: "order-service"

  - job_name: "ftgo-courier-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ftgo-courier-service:8084"]
        labels:
          service: "courier-service"

  - job_name: "ftgo-api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ftgo-api-gateway:8085"]
        labels:
          service: "api-gateway"
