apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: ftgo-platform
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - mysql/deployment.yaml
  - mysql/service.yaml
  - mysql/configmap.yaml
  - mysql/sealed-secret.yaml
  - mysql/pvc.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - keycloak/configmap.yaml
  - ftgo-consumer-service/deployment.yaml
  - ftgo-consumer-service/service.yaml
  - ftgo-consumer-service/configmap.yaml
  - ftgo-consumer-service/sealed-secret.yaml
  - ftgo-consumer-service/hpa.yaml
  - ftgo-restaurant-service/deployment.yaml
  - ftgo-restaurant-service/service.yaml
  - ftgo-restaurant-service/configmap.yaml
  - ftgo-restaurant-service/hpa.yaml
  - ftgo-order-service/deployment.yaml
  - ftgo-order-service/service.yaml
  - ftgo-order-service/configmap.yaml
  - ftgo-order-service/hpa.yaml
  - ftgo-courier-service/deployment.yaml
  - ftgo-courier-service/service.yaml
  - ftgo-courier-service/configmap.yaml
  - ftgo-courier-service/hpa.yaml
  - ingress/ingress.yaml
