apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-order-service
  labels:
    app: ftgo-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftgo-order-service
  template:
    metadata:
      labels:
        app: ftgo-order-service
    spec:
      containers:
        - name: ftgo-order-service
          image: ftgo/order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
