plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

group = 'com.ftgo'
version = '1.0.0'
sourceCompatibility = '11'
targetCompatibility = '11'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:2.6.3'
    }
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.security:spring-security-oauth2-resource-server'
    api 'org.springframework.security:spring-security-oauth2-jose'

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'com.nimbusds:nimbus-jose-jwt:9.22'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator'
}

test {
    useJUnitPlatform()
}
