name: Java 11→21 Migration Validation

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '21']

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Build and Test
        run: ./gradlew clean test --no-daemon --warning-mode all
