name: Java 11→21 Migration Validation

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        java: ['11', '21']

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Java code
        run: ./gradlew generateJava --no-daemon --info
        timeout-minutes: 20

      - name: Build and Test
        run: ./gradlew clean test --no-daemon --warning-mode all --parallel
        timeout-minutes: 25
