plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation "org.springframework.boot:spring-boot-gradle-plugin:${libs.versions.spring.boot.get()}"
    implementation "io.spring.gradle:dependency-management-plugin:${libs.versions.spring.dependency.get()}"
    implementation "com.diffplug.spotless:spotless-plugin-gradle:${libs.versions.spotless.get()}"
}
